name: Deploy Telegram Recipe Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Check files
      run: |
        echo "Listing files in the repository:"
        ls -la
        echo "Displaying contents of requirements.txt:"
        cat requirements.txt
        echo "Displaying contents of bot.py:"
        cat bot.py
        echo "Displaying contents of .env:"
        cat .env

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify installed packages
      run: |
        source venv/bin/activate
        pip list

    - name: Run bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
      run: |
        source venv/bin/activate
        python bot.py
